/*

				BACKUP FULL, DIFFERENTIAL E BACKUP DE LOG

*/

-- ESTE É O PRIMEIRO BACKUP QUE FAREMOS, O BKP FULL DO BANCO ADVENTURE WORKS
-- PRIMEIRO, IREI APENAS ESCREVER A SINTAXE E DEPOIS, IREMOS CRIAR O ARQUIVO DE BACKUP

-- SINTAXE DO BACKUP FULL, DIFFERENTIAL E LOG
-- O WITH ESPECIFICA AS OPÇÕES QUE SERÃO USADAS NO ARQUIVO DE BACKUP, ESPECIFIQUEI AS MAIS USADAS E NO POST EXPLICAREI CADA UMA
BACKUP DATABASE [NOME_DATABASE]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\NOME_ARQUIVO.BAK'
WITH INIT, COMPRESSION, CHECKSUM, STATS = 20

BACKUP DATABASE [NOME_DATABASE]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\NOME_ARQUIVO.BAK'
WITH DIFFERENTIAL, INIT, COMPRESSION, CHECKSUM, STATS = 20

BACKUP DATABASE [sample]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\SAMPLE.BAK'
MIRROR TO DISK = 'F:\SQLBIM.BKP\BAK & TRN - Copy\SAMPLE.BAK'
WITH CHECKSUM, INIT, COMPRESSION, STATS = 40, FORMAT, ENCRYPTION(   
															ALGORITHM = AES_128,
															SERVER CERTIFICATE = NOME_CERTIFICADO)

-- ALTERAR O TIPO DE ARQUIVO PARA TRN AO INVÉS DE USAR BAK
BACKUP LOG [NOME_DATABASE]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\NOME_ARQUIVO.TRN'
WITH INIT, COMPRESSION, CHECKSUM, STATS = 20

-- CRIANDO O ARQUIVO DE BACKUP FULL DO [AdventureWorks2017]
-- O INIT SOBREESCREVE NO ARQUIVO DE BACKUP NO DISCO
BACKUP DATABASE ADVENTUREWORKS2017
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\ADVWORKS2017.BAK'
WITH INIT, COMPRESSION, CHECKSUM, STATS = 40

-- BACKUP FULL SEM INIT
-- SE NÃO ESPECIFICAR O INIT NO COMANDO DE BACKUP, ELE IRÁ ANEXAR UM ARQUIVO NO OUTRO
-- O NOINIT ELE FAZ UM APPEND DOS ARQUIVOS DE BACKUP, CRIANDO UM CONJUNTO DE MIDIA DEBACKUP
BACKUP DATABASE [AdventureWorks2017]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\ADVWORKSNOINIT.BAK'
WITH CHECKSUM, COMPRESSION, STATS = 40


-- REALIZANDO BACKUP DIFFERENTIAL
-- A SINTAXE DO BACKUP DIFFERENTIAL É BASICAMENTE A MESMA O QUE MUDA É A ESPECIFICAÇÃO NA CLÁUSULA WITH
-- REPARE QUE PARA O DIFFERENTIAL, USAREMOS O PRÓPRIO NOME COMO UMA OPTION 
BACKUP DATABASE [AdventureWorks2017]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\ADVWORKS2017_DIFF.BAK'
WITH DIFFERENTIAL, CHECKSUM, INIT, COMPRESSION, STATS = 40

-- BACKUP DE LOG
-- BASICAMENTE A MESMA SINTAXE, DEVENDO APENAS IDENTIFICAR QUE QUEREMOS CRIAR O BACKUP DE LOG
BACKUP LOG [AdventureWorks2017]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\ADVWORKS2017_LOG.TRN'
WITH CHECKSUM, COMPRESSION, INIT, STATS = 40

-- BACKUP FULL COM ARQUIVOS DIVIDIDOS
-- SE UM BANCO FOR MUITO GRANDE E A OPERAÇÃO CONSUMIR MUITO TEMPO, PODEMOS DIVIDIR EM PARTES O ARQUIVO DE BACKUP
-- O COMANDO NÃO MUDA MUITO, APENAS ESPECIFICA A QUANTIDADE DE ARQUIVOS QUE VAMOS DIVIDIR
BACKUP DATABASE [WideWorldImporters]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\WWIMPORTERS_1.BAK',
   DISK = 'F:\SQLBIM.BKP\BAK & TRN\WWIMPORTERS_2.BAK',
   DISK = 'F:\SQLBIM.BKP\BAK & TRN\WWIMPORTERS_3.BAK',
   DISK = 'F:\SQLBIM.BKP\BAK & TRN\WWIMPORTERS_4.BAK'
WITH INIT, CHECKSUM, COMPRESSION, STATS =  40

-- BACKUP COM ENCRYPTION E MIRROR
BACKUP DATABASE [sample]
TO DISK = 'F:\SQLBIM.BKP\BAK & TRN\SAMPLE.BAK'
MIRROR TO DISK = 'F:\SQLBIM.BKP\BAK & TRN - Copy\SAMPLE.BAK'
WITH CHECKSUM, INIT, COMPRESSION, STATS = 40, FORMAT, ENCRYPTION(   
															ALGORITHM = AES_128,
															SERVER CERTIFICATE = TDECERT)

