/*

========= DYNAMIC DATA MASKING =========

*/

-- INSERINDO DADOS NAS COLUNAS DE EXEMPLO
INSERT INTO DBO.ALWAYSENC (CARD_COL, EMAIL_COL, RG, CPF)
SELECT '987447896647','AZUREDDM@HOTMAIL.COM','4358417493','18472358722'
GO 5

-- APLICANDO O DDM MASCARANDO O ENDEREÇO DE E-MAIL
-- AS FUNÇÕES DE MASCARAMENTO SÃO NATIVAS DO SQL SERVER
-- CRIE UM SEGUNDO USUÁRIO SOMENTE COM A PERMISSÃO DE SELECT
ALTER TABLE DBO.ALWAYSENC
ALTER COLUMN EMAIL_COL ADD MASKED 
	  WITH (FUNCTION = 'EMAIL()')

-- MASCARANDO O RG
ALTER TABLE DBO.ALWAYSENC
ALTER COLUMN RG ADD MASKED
	  WITH (FUNCTION = 'PARTIAL(0,"XXX-XXX-X",1)')

-- MASCARANDO O CPF
ALTER TABLE DBO.ALWAYSENC
ALTER COLUMN CPF ADD MASKED
	  WITH (FUNCTION = 'PARTIAL(0,"XXX-XXX-",2)')

